title: Elementh Foundation
author: Elementh
email: panoramedia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Elementh Foundation

twitter_username: macrod68
github_username:  macrod68

sass:
    style: compressed