title: Starter Template
author: Panoramedia
email: panoramedia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A Site Starter Materialize Templates for Jekyll

twitter_username: macrod68
github_username:  macrod68

sass:
    style: compressed